name:       renamer
version:    1.0.0
synopsis:   Tool to rename photos
github:     jwiegley/renamer
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    BSD3

ghc-options:
   - -Wall
   - -Wno-missing-home-modules
   - -fprof-auto

description:
  Tool to rename photos

dependencies:
  - base                 >= 4.7
  - aeson
  - containers           >= 0.6
  - directory
  - filepath
  - lens                 >= 4.9
  - optparse-applicative >= 0.10
  - pretty-show
  - process
  - regex-tdfa
  - time                 >= 1.4
  - transformers         >= 0.3
  - unordered-containers >= 0.2

executables:
  renamer:
    main: Main.hs
    ghc-options: -threaded
