#!/usr/bin/env bash
set -euo pipefail

# Run tests with coverage enabled
cabal test -j --enable-coverage --test-show-details=direct 2>&1

# Find the tix file generated by the test run
TIX=$(find dist-newstyle -name 'renamer-tests.tix' 2>/dev/null | head -1)
if [ -z "$TIX" ]; then
  echo "WARNING: No coverage data found"
  exit 0
fi

# Build --hpcdir flags from discovered mix directories.
# hpc expects the parent directory that contains the package-named subdirectories
# (e.g., renamer-1.0.0-inplace/), so we point at the mix/ directory.
HPCDIR_FLAGS=()
while IFS= read -r mixdir; do
  HPCDIR_FLAGS+=(--hpcdir="$mixdir")
done < <(find dist-newstyle -path '*/extra-compilation-artifacts/hpc/vanilla/mix' -type d 2>/dev/null | sort -u)

if [ ${#HPCDIR_FLAGS[@]} -eq 0 ]; then
  echo "WARNING: No HPC mix directories found"
  exit 0
fi

# Extract expression coverage percentage
COVERAGE=$(hpc report "$TIX" "${HPCDIR_FLAGS[@]}" 2>/dev/null \
  | grep 'expressions used' \
  | grep -oE '[0-9]+' \
  | head -1)

if [ -z "$COVERAGE" ]; then
  echo "WARNING: Could not parse coverage data"
  exit 0
fi

echo "Coverage: ${COVERAGE}% expressions used"

# Check against stored threshold
THRESHOLD=$(cat .coverage-threshold 2>/dev/null || echo "0")
if [ "$COVERAGE" -lt "$THRESHOLD" ]; then
  echo "ERROR: Coverage dropped from ${THRESHOLD}% to ${COVERAGE}%"
  exit 1
fi

# Report if coverage improved (update .coverage-threshold manually to ratchet)
if [ "$COVERAGE" -gt "$THRESHOLD" ]; then
  echo "Coverage improved: ${THRESHOLD}% -> ${COVERAGE}%"
  echo "Run: echo $COVERAGE > .coverage-threshold"
fi
